### ISSUE TITLE
NameError: name 'hotpep_genes' is not defined

### ISSUE THREAD

**Issue by FranckLejzerowicz** [linnabrown/run_dbcan#23]
Hello,

Thanks for the nice tool combining CAZy and powerful sequence matching tools!
I have a little problem with the usage though:

If I run this command and only call for DIAMOND (i.e. option ` -t diamond ` only):

```

run_dbcan.py ${locdir}/my/path/to/this/metaspades_contigs.fasta prok --out_dir ${locdir}/my/path/to/this/directory -t diamond --db_dir ${locdir}/home/flejzerowicz/databases/dbCAN/personalized_database --dia_cpu 12

```

(`${locdir}` is a correct path so that the entire path is absolute)

I get the following stdout with an error that seem to relate to the use of Hotpep, which I do not wish to use - any clue?

```

Warning:  Sequence is long (max 32000000 for training).
Training on the first 32000000 bases.

***************************1. DIAMOND start*************************************************


diamond v0.9.26.127 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 12
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /panfs/panfs1.ucsd.edu/panscratch/flejzerowicz/my/path/to/this/directory
Opening the database...  [0.000278s]
#Target sequences to report alignments for: 1
Opening the input file...  [0.001197s]
Opening the output file...  [0.003111s]
Loading query sequences...  [0.637969s]
Masking queries...  [7.28999s]
Building query seed set...  [0.032979s]
Algorithm: Double-indexed
Building query histograms...  [1.3517s]
Allocating buffers...  [4.2e-05s]
Loading reference sequences...  [0.00264s]
Masking reference...  [0.157967s]
Building reference histograms...  [0.030341s]
Allocating buffers...  [3.4e-05s]
Initializing temporary storage...  [0.118368s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.069642s]
Building query index...  [2.09558s]
Building seed filter...  [0.185448s]
Searching alignments...  [0.477442s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [0.072169s]
Building query index...  [2.38556s]
Building seed filter...  [0.186147s]
Searching alignments...  [0.235003s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [0.046568s]
Building query index...  [2.39268s]
Building seed filter...  [0.17724s]
Searching alignments...  [0.210358s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [0.037975s]
Building query index...  [2.0244s]
Building seed filter...  [0.184022s]
Searching alignments...  [0.226961s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [0.038416s]
Building query index...  [1.99487s]
Building seed filter...  [0.184617s]
Searching alignments...  [0.194988s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [0.045087s]
Building query index...  [2.30156s]
Building seed filter...  [0.176901s]
Searching alignments...  [0.186611s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [0.046578s]
Building query index...  [2.3874s]
Building seed filter...  [0.183456s]
Searching alignments...  [0.170639s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [0.035853s]
Building query index...  [1.94297s]
Building seed filter...  [0.175712s]
Searching alignments...  [0.177544s]
Deallocating buffers...  [4e-06s]
Computing alignments...  [3.97316s]
Deallocating reference...  [5e-06s]
Loading reference sequences...  [4.8e-05s]
Deallocating buffers...  [0.011524s]
Deallocating queries...  [0.008446s]
Loading query sequences...  [4e-05s]
Closing the input file...  [5.8e-05s]
Closing the output file...  [0.005646s]
Closing the database file...  [4.6e-05s]
Deallocating taxonomy...  [1.5e-05s]
Total time = 34.884s
Reported 810 pairwise alignments, 810 HSPs.
810 queries aligned.
***************************1. DIAMOND end***************************************************
Preparing overview table from hmmer, hotpep and diamond output...
Traceback (most recent call last):
  File "/home/flejzerowicz/usr/miniconda3/envs/cazy/bin/run_dbcan.py", line 567, in <module>
    if len(hotpep_genes) > 0:
NameError: name 'hotpep_genes' is not defined

```

I do not understand why the `hotpep_genes` object would need to be defined in the script when the -t option only ask using diamond (I found in the code that it is anyway set to an empty list but here it seems to not be the case...)

Note that my directory `${locdir}/home/flejzerowicz/databases/dbCAN/personalized_database` contains:
* the unchanged HMM database (files `dbCAN.txt`, `dbCAN.txt.h3f`, `dbCAN.txt.h3i`, `dbCAN.txt.h3m` and `dbCAN.txt.h3p`)
* a custom subset CAZy database (chosen unique sequences from the GCF_#.fasta files turned to a DIAMOND database using diamond version 0.9.26 [the version shipped with dbCAN]).

I'm also running `run_dbcan.py` on the native database provided with the tools (still with `-t diamond`) and I'll follow up about what happens.

Thanks for the help!
Franck

**Comment by linnabrown** [comment]
Thanks for your issue. It is because we think all of the users will use HotPep also.
Sorry for the inconvenience.
https://github.com/linnabrown/run_dbcan/commit/e7ae63304f7e99ea1c41b9465b72d93d145b3595

**Comment by FranckLejzerowicz** [comment]
Thanks! - I'm gonna retry now

**Comment by linnabrown** [comment]
This problem has been solved in the new package.
Please use this command

```
pip install run-dbcan==2.0.1 --user
```

**Comment by dadahan** [comment]
It appears this problem is back with v2.0.3 released on Jan 12, 2020 `pip install run-dbcan==2.0.3 --user`
